apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-controller
  namespace: controller
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-controller
  template:
    metadata:
      labels:
        app: python-controller
    spec:
      serviceAccountName: retry-controller-sa
      securityContext:
        runAsUser: 0
      containers:
        - name: controller
          image: python
          command: ["sleep"]
          args: ["10000000"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: retry-controller-sa
 namespace: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: controller
  name: retry-controller-role
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retry-controller-rolebinding
  namespace: controller
subjects:
- kind: ServiceAccount
  name: retry-controller-sa
  namespace: controller
roleRef:
  kind: Role
  name: retry-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: retry-controller-clusterrole
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retry-controller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: retry-controller-sa
  namespace: controller  # Namespace of the ServiceAccount
roleRef:
  kind: ClusterRole
  name: retry-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
